<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>FFXIVAura</AssemblyName>
    <RootNamespace>FFXIVAura</RootNamespace>
    <Version>0.1.0.14</Version>
    <AssemblyVersion>0.1.0.14</AssemblyVersion>
    <FileVersion>0.1.0.14</FileVersion>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FFXIVAura.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dalamud" HintPath="$(APPDATA)\XIVLauncherKR\addon\Hooks\15.0.2.2\Dalamud.dll" Private="false" />
    <Reference Include="Dalamud.Bindings.ImGui" HintPath="$(APPDATA)\XIVLauncherKR\addon\Hooks\15.0.2.2\Dalamud.Bindings.ImGui.dll" Private="false" />
    <Reference Include="FFXIVClientStructs" HintPath="$(APPDATA)\XIVLauncherKR\addon\Hooks\15.0.2.2\FFXIVClientStructs.dll" Private="false" />
    <Reference Include="InteropGenerator.Runtime" HintPath="$(APPDATA)\XIVLauncherKR\addon\Hooks\15.0.2.2\InteropGenerator.Runtime.dll" Private="false" />
    <Reference Include="Lumina" HintPath="$(APPDATA)\XIVLauncherKR\addon\Hooks\15.0.2.2\Lumina.dll" Private="false" />
    <Reference Include="Lumina.Excel" HintPath="$(APPDATA)\XIVLauncherKR\addon\Hooks\15.0.2.2\Lumina.Excel.dll" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Data\abilities.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
