global using System.Numerics;
global using System.Text.Json;
global using Dalamud.Bindings.ImGui;
global using Dalamud.Game.ClientState.Party;
global using Dalamud.Game.ClientState;
global using Dalamud.Game.ClientState.Conditions;
global using Dalamud.Game.ClientState.Objects.Enums;
global using Dalamud.Game.ClientState.Objects.Types;
global using Dalamud.Game.ClientState.Statuses;
global using Dalamud.Game.Command;
global using Dalamud.Interface.GameFonts;
global using Dalamud.Interface.ManagedFontAtlas;
global using Dalamud.Interface.Textures;
global using Dalamud.Interface.Textures.TextureWraps;
global using Dalamud.Utility;
global using Dalamud.IoC;
global using Dalamud.Plugin;
global using Dalamud.Plugin.Services;
global using FFXIVClientStructs.FFXIV.Client.Game;
global using Lumina.Data.Files;
global using GameAction = Lumina.Excel.Sheets.Action;
global using GameActionTransient = Lumina.Excel.Sheets.ActionTransient;
global using GameStatus = Lumina.Excel.Sheets.Status;
